export const CART_ACTION_TYPES = {
  TOGGLE_CART: 'cart/TOGGLE_CART',
  UPDATE_CART: 'cart/UPDATE_CART',
  ADD_CART: 'cart/ADD_CART',
  COUNT_CART: 'cart/COUNT_CART',
  TOTAL_PRICE: 'cart/TOTAL_PRICE',
};
 